CREATE DATABASE INSTITUICAO;
CREATE TABLE ALUNO (
 CODIGOALUNO int NOT NULL,
 NOME varchar(90) NOT NULL,
 SEXO char(1) NOT NULL,
 DTNASCIMENTO date NOT NULL,
 EMAIL varchar(30) NULL,
 CONSTRAINT ALUNO_pk PRIMARY KEY (CODIGOALUNO));

INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (1,'JOSÉ FRANCISCO
TERRA','M','28/10/1989','JFT@GMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (2,'ANDREY COSTA
FILHO','M','20/10/1999','ANDREYCF@HOTMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (3,'PATRÍCIA TORRES LOUREIRO','F','20/10/1980',
'PTORRES@GMAIL.COM');
INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (4,'CARLA MARIA MACIEL','F','20/11/1996',NULL);
INSERT INTO ALUNO (CODIGOALUNO, NOME, SEXO, DTNASCIMENTO,EMAIL) VALUES (5,'LEILA SANTANA COSTA','F','20/11/2001',NULL);

CREATE TABLE FUNCIONARIO (
 CODIGOFUNCIONARIO int NOT NULL,
 NOME char(90) NOT NULL,
 CPF char(15) NULL,
 SEXO char(1) NOT NULL,
 DTNASCIMENTO date NOT NULL,
 SALARIO real NULL,
 CONSTRAINT FUNCIONARIO_pk PRIMARY KEY (CODIGOFUNCIONARIO));
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO)
VALUES (1,'ROBERTA SILVA BRASIL',NULL,'F','20/02/1980',7000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO)
VALUES (2,'MARIA SILVA BRASIL',NULL,'F','20/09/1988',9500);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO)
VALUES (3,'GABRIELLA PEREIRA LIMA',NULL,'F','20/02/1990',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO)
VALUES (4,'MARCOS PEREIRA BRASIL',NULL,'M','20/02/1999',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO)
VALUES (5,'HEMERSON SILVA BRASIL',NULL,'M','20/12/1992',4000);
CREATE TABLE CURSO (
 CODIGOCURSO int NOT NULL,
 DISCIPLINA varchar(190) NOT NULL,
 CARGAHORARIA time NOT NULL,
 CONSTRAINT curso_pk PRIMARY KEY (CODIGOCURSO));
CREATE TABLE INSCRICAO (
 CODIGOINSCRICAO int NOT NULL,
 DATACRIACAO date NULL,
 CONSTRAINT INSCRICAO_PK PRIMARY KEY (CODIGOINSCRICAO),
 FOREIGN KEY (CODIGOALUNO) REFERENCES ALUNO (CODIGOALUNO),
 FOREIGN KEY (CODIGOFUNCIONARIO) REFERENCES FUNCIONARIO (CODIGOFUNCIONARIO),
 FOREIGN KEY (CODIGOCURSO) REFERENCES CURSO (CODIGOCURSO)
 );

SELECT * FROM ALUNO;
SELECT * FROM FUNCIONARIO;
SELECT * FROM CURSO;
